### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by yosefHesham** [yosefHesham/Catalog-My-Things#20]
Catalog-My-Things Kanban board ^_^
---
https://github.com/users/yosefHesham/projects/2/views/1

We are group of 3.

And the distribution of tasks will be:
Tasks of Team Member 1 => @yosefHesham 
Tasks of Team Member 2 => @momotsow 
Tasks of Team Member 3=> @vanelnw

**Comment by GzimAsani** [comment]
### Hello, @yosefHesham, @vanelnw and @momotsow               :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with adding descriptions for all the cards  :+1: 

 ## Required Changes 

- [ ] Each of the bullet point on group task section should have its own separate task, you should not combine them together few of them on one task
![image](https://user-images.githubusercontent.com/62705947/218573525-c0dca526-4396-4a83-8cff-9808220d1094.png)
- [ ]  All of the team members have combined few bullet points in one task. Please be reminded that each bullet point should have its own separate task and then assigned accordingly. Please implement this


 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by brytebee** [comment]
Hi Team👋,

##

### Highlights💡
- A link to the Kanban board is specified.✔️ 
- The team member size is stated.✔️
- All required columns are present.✔️
- Cards are distributed fairly.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
- A couple of your cards are missing descriptions.

![image](https://user-images.githubusercontent.com/27709832/218578505-00122bde-8a01-458d-b835-c758b68e0a78.png)

Kindly add descriptions.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by t-yanick** [comment]
# STATUS: MILESTONE APPROVED

Hello, @yosefHesham, @vanelnw and @momotsow 👋

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  All cards having descriptions
:heavy_check_mark: Link to Kaban board provided
:heavy_check_mark:  Collaborative work and fair distribution

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
